apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciup-wash-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciup-wash-bot
  template:
    metadata:
      labels:
        app: ciup-wash-bot
    spec:
      containers:
      - name: ciup-wash-bot
        image: eordyan/ciup-wash-bot:1.3
        env:
        - name: DB_PATH
          value: /app/data/reservations.db
        volumeMounts:
        - name: ciup-wash-bot-volume
          mountPath: /app/data
      volumes:
      - name: ciup-wash-bot-volume
        persistentVolumeClaim:
          claimName: ciup-wash-bot-pvc

